// Shape of `web/public/wasm/manifest.json`, generated by `web/scripts/build-manifest.mjs`
// at Pages-deploy time. The runtime fetches this file at app startup and uses it to
// populate the version dropdown.

export type WasmSource =
  | { kind: "bundled"; jsUrl: string; wasmUrl: string }
  | { kind: "remote"; jsUrl: string; wasmUrl: string };

// Tag releases come from llvmorg-* tags (auto- or tag-based manual releases).
// Commit snapshots come from SHA-based manual releases and live in their own
// dropdown section in the UI so they don't crowd the stable picker.
export type WasmReleaseKind = "tag" | "commit";

export interface WasmRelease {
  tag: string;
  name: string;
  slug: string;
  kind: WasmReleaseKind;
  publishedAt: string;
  prerelease: boolean;
  bundled: boolean;
  // For bundled entries: path fragment relative to `${BASE_URL}wasm/`, e.g.
  //   "release_llvmorg-22.1.6/instcombine_driver.js".
  // For remote entries: absolute https URL of the GitHub Release asset.
  jsAsset: string;
  wasmAsset: string;
}

export interface WasmManifest {
  generatedAt: string;
  defaultTag: string | null;
  releases: WasmRelease[];
}

export function releaseToSource(
  release: WasmRelease,
  baseUrl: string,
): WasmSource {
  if (release.bundled) {
    return {
      kind: "bundled",
      jsUrl: `${baseUrl}wasm/${release.jsAsset}`,
      wasmUrl: `${baseUrl}wasm/${release.wasmAsset}`,
    };
  }
  return { kind: "remote", jsUrl: release.jsAsset, wasmUrl: release.wasmAsset };
}
